services:
  - docker:dind

stages:
  - build

variables:
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}

build:
  image: docker
  stage: build
  only:
    - main
  script:
    - echo "VITE_API_BASE_URL=https://api.chestniyznak.uz" > .env
    - docker image build . -t ${IMAGE}
    - docker image push ${IMAGE}
